apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy:
    sha256: {}
  local: {}
  artifacts:
  - image: opensourcebapu/mongodb-opsmgr-centos
    docker:
      dockerfile: Dockerfile
    context: ./

deploy:
  helm:
    releases:
    - name: test
      namespace: mongodb
      chartPath: mongo-opsmgr-helm
      #wait: true
      valuesFiles:
      - mongo-opsmgr-helm/values.yaml
      #recreatePods will pass --recreate-pods to helm upgrade
      #recreatePods: true
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.
      #setValues:
#some.key: someValue