# Default values for mongo-opsmgr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  name: opensourcebapu/mongodb-opsmgr-centos
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  clusterIP: None
  port: 8080

env:
  MMS_USER: mongodb-mms                                    #Change this if you use a custom USER in custom image build, and or if you run as root for debug mode
  ENC_KEY_PATH: /etc/mongodb-mms/gen.key                   #Default path is /etc/mongodb-mms/gen.key

#Values to pass to conf file for connecting to appdb
appdb:
  host: mongo-replicaset-0:27017,mongo-replicaset-1:27017,mongo-replicaset-2:27017
  #port: 27017
  #username:
  #password:

ingress:
  enabled: false
  annotations: 
    #nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
  paths:
    - /
  hosts:
    - opsmgr.example.local
  tls: []
    # - secretName: tls-secret
    #   hosts:
    #     - opsmgr.example.local

resources:
   #refer to https://docs.opsmanager.mongodb.com/current/core/requirements/ for sizing info and/or contact your MongoDB rep
   limits:
    cpu: 2000m
    memory: 2Gi
   requests:
    cpu: 500m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

genKeyCreation: "No"                #Scrapping this idea for genkey-confiogmap.yaml since binary key isn't able to be put in secret or configmap

securityContext:
  enabled: true
  runAsUser: 999                    #999 is the mongodb-mms user in this version of the image
  fsGroup: 998                      #998 is the mongodb-mms group in this version of the image
  runAsNonRoot: true

persistentVolume:
  keyVol:
    enabled: true                  #Enabling this creates a PVC for gen.key file, approach to this might change for HA
    ## Mongodb OpsMgr gen.key Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessModes:
      - ReadWriteOnce
    size: 50Mi
  releaseVol:
    enabled: true                  #Enabling this creates a PVC for mongodb release versions
    ## Mongodb ops mgr release versions Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessModes:
      - ReadWriteOnce
    size: 5Gi    