{{ if ne .Values.genKeyCreation "No" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongo-opsmgr.fullname" . }}-genkey-configmap
  labels:
    app.kubernetes.io/name: {{ include "mongo-opsmgr.name" . }}
    helm.sh/chart: {{ include "mongo-opsmgr.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
binaryData:
  gen.key: |
{{ tpl (.Files.Get "secrets/gen.key") . | indent 4 }}
{{ end }}